"""First

Revision ID: 076684e0a0d3
Revises: 
Create Date: 2023-05-04 05:52:44.355476

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "076684e0a0d3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_types_id"), "orders_types", ["id"], unique=False)
    op.create_table(
        "zip_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zip_codes_id"), "zip_codes", ["id"], unique=False)
    op.create_table(
        "streets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_streets_id"), "streets", ["id"], unique=False)
    op.create_table(
        "states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_states_id"), "states", ["id"], unique=False)
    op.create_table(
        "phones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phones_id"), "phones", ["id"], unique=False)
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)
    op.create_table(
        "customers_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("register_name", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_accounts_id"), "customers_accounts", ["id"], unique=False
    )
    op.create_table(
        "customers_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("is_tester", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_emails_id"), "customers_emails", ["id"], unique=False
    )
    op.create_table(
        "editions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_editions_id"), "editions", ["id"], unique=False)
    op.create_table(
        "customers_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("register_name", sa.String(length=255), nullable=False),
        sa.Column("creating_date", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("last_modified_date", sa.DateTime(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("street_id", sa.Integer(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("zip_id", sa.Integer(), nullable=True),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.Column("phone_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["phone_id"],
            ["phones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["street_id"],
            ["streets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zip_id"],
            ["zip_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_data_id"), "customers_data", ["id"], unique=False
    )
    op.create_table(
        "keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Numeric(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column("count_license", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_beta_key", sa.Boolean(), nullable=False),
        sa.Column("register_name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keys_id"), "keys", ["id"], unique=False)
    op.create_table(
        "products_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("is_main_product", sa.Boolean(), nullable=False),
        sa.Column("lifetime", sa.Boolean(), nullable=True),
        sa.Column("versioned", sa.Boolean(), nullable=True),
        sa.Column("upgradable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_types_id"), "products_types", ["id"], unique=False
    )
    op.create_table(
        "products_vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_vendor_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.BigInteger(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("added", sa.DateTime(), nullable=False),
        sa.Column("last_changed", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_vendors_id"), "products_vendors", ["id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_product_id", sa.Numeric(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Numeric(), nullable=True),
        sa.Column("platform_id", sa.Integer(), nullable=True),
        sa.Column("edition_id", sa.Integer(), nullable=True),
        sa.Column("previous_edition_id", sa.Integer(), nullable=True),
        sa.Column("previous_version", sa.Numeric(), nullable=True),
        sa.Column("previous_platform_id", sa.Integer(), nullable=True),
        sa.Column("is_released", sa.Boolean(), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("is_subscribtion", sa.Boolean(), nullable=False),
        sa.Column("active_months", sa.Integer(), nullable=True),
        sa.Column("url_for_download", sa.String(length=255), nullable=True),
        sa.Column("coupon", sa.String(length=255), nullable=True),
        sa.Column("remove_from_cross_selling_list", sa.Boolean(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_edition_id"],
            ["editions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["products_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["products_vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_id"), "sources", ["id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("num_license", sa.Integer(), nullable=True),
        sa.Column("purchase_id", sa.Numeric(), nullable=False),
        sa.Column("running_no", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("comments", sa.String(length=255), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("payment_type_id", sa.Integer(), nullable=True),
        sa.Column("previous_order_id", sa.Integer(), nullable=True),
        sa.Column("next_order_id", sa.Integer(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("is_in_processing", sa.Boolean(), nullable=False),
        sa.Column("internal_order_type_id", sa.Integer(), nullable=True),
        sa.Column("key_id", sa.Integer(), nullable=True),
        sa.Column("last_paid_rebilling_number", sa.Numeric(), nullable=True),
        sa.Column("addtional1", sa.String(length=255), nullable=True),
        sa.Column("addtional2", sa.String(length=255), nullable=True),
        sa.Column("is_subscribtion", sa.Boolean(), nullable=True),
        sa.Column("source_order_id", sa.Integer(), nullable=True),
        sa.Column("last_changed", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["key_id"],
            ["keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["next_order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_type_id"],
            ["orders_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)

    op.create_table(
        "invalid_customers_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_email_id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_email_id"],
            ["customers_emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invalid_customers_emails_id"),
        "invalid_customers_emails",
        ["id"],
        unique=False,
    )

    op.create_table(
        "unsubscribed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_email_id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_email_id"],
            ["customers_emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unsubscribed_id"), "unsubscribed", ["id"], unique=False)
    op.create_table(
        "accounts_customers_relations_v2",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["customers_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers_data.id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "customer_id"),
    )
    op.create_index(
        op.f("ix_accounts_customers_relations_v2_account_id"),
        "accounts_customers_relations_v2",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounts_customers_relations_v2_customer_id"),
        "accounts_customers_relations_v2",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "customer_data_customer_email_links_v2",
        sa.Column("customer_email_id", sa.Integer(), nullable=False),
        sa.Column("customer_data_id", sa.Integer(), nullable=False),
        sa.Column("creating_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_data_id"],
            ["customers_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_email_id"],
            ["customers_emails.id"],
        ),
        sa.PrimaryKeyConstraint("customer_email_id", "customer_data_id"),
    )
    op.create_index(
        op.f("ix_customer_data_customer_email_links_v2_customer_data_id"),
        "customer_data_customer_email_links_v2",
        ["customer_data_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_data_customer_email_links_v2_customer_email_id"),
        "customer_data_customer_email_links_v2",
        ["customer_email_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_data_customer_email_links_v2_customer_email_id"),
        table_name="customer_data_customer_email_links_v2",
    )
    op.drop_index(
        op.f("ix_customer_data_customer_email_links_v2_customer_data_id"),
        table_name="customer_data_customer_email_links_v2",
    )
    op.drop_table("customer_data_customer_email_links_v2")
    op.drop_index(
        op.f("ix_accounts_customers_relations_v2_customer_id"),
        table_name="accounts_customers_relations_v2",
    )
    op.drop_index(
        op.f("ix_accounts_customers_relations_v2_account_id"),
        table_name="accounts_customers_relations_v2",
    )
    op.drop_table("accounts_customers_relations_v2")
    op.drop_index(op.f("ix_unsubscribed_id"), table_name="unsubscribed")
    op.drop_table("unsubscribed")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(
        op.f("ix_invalid_customers_emails_id"), table_name="invalid_customers_emails"
    )
    op.drop_table("invalid_customers_emails")
    op.drop_index(op.f("ix_customers_data_id"), table_name="customers_data")
    op.drop_table("customers_data")
    op.drop_index(op.f("ix_zip_codes_id"), table_name="zip_codes")
    op.drop_table("zip_codes")
    op.drop_index(op.f("ix_streets_id"), table_name="streets")
    op.drop_table("streets")
    op.drop_index(op.f("ix_states_id"), table_name="states")
    op.drop_table("states")
    op.drop_index(op.f("ix_sources_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_products_vendors_id"), table_name="products_vendors")
    op.drop_table("products_vendors")
    op.drop_index(op.f("ix_products_types_id"), table_name="products_types")
    op.drop_table("products_types")
    op.drop_index(op.f("ix_phones_id"), table_name="phones")
    op.drop_table("phones")
    op.drop_index(op.f("ix_orders_types_id"), table_name="orders_types")
    op.drop_table("orders_types")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_keys_id"), table_name="keys")
    op.drop_table("keys")
    op.drop_index(op.f("ix_editions_id"), table_name="editions")
    op.drop_table("editions")
    op.drop_index(op.f("ix_customers_emails_id"), table_name="customers_emails")
    op.drop_table("customers_emails")
    op.drop_index(op.f("ix_customers_accounts_id"), table_name="customers_accounts")
    op.drop_table("customers_accounts")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
