"""delete purchase from keys

Revision ID: 3bc0f5fcde71
Revises: c0b7114f9d30
Create Date: 2023-05-14 10:44:41.750417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bc0f5fcde71"
down_revision = "c0b7114f9d30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
