"""add product group to products

Revision ID: 52034d9e6e26
Revises: 978a3bd54d2b
Create Date: 2023-05-16 15:56:53.725484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52034d9e6e26"
down_revision = "978a3bd54d2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("product_group_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "products", "products_groups", ["product_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "product_group_id")
    # ### end Alembic commands ###
