"""Two

Revision ID: 52896fbc192b
Revises: 076684e0a0d3
Create Date: 2023-05-04 06:14:15.580942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52896fbc192b"
down_revision = "076684e0a0d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "keys", "orders", ["purchase_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "keys", type_="foreignkey")
    # ### end Alembic commands ###
