"""fix tables

Revision ID: 7ad587ad0fd1
Revises: 52896fbc192b
Create Date: 2023-05-13 13:30:12.311291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ad587ad0fd1"
down_revision = "52896fbc192b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer_data_customer_email_links_v2",
        "creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.alter_column(
        "customer_data_customer_email_links_v2",
        "last_modified_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.alter_column(
        "customers_data",
        "creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.alter_column(
        "customers_data",
        "last_modified_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.drop_column("customers_emails", "is_tester")

    op.alter_column(
        "invalid_customers_emails",
        "create_date",
        new_column_name="creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )

    op.alter_column(
        "keys",
        "create_date",
        new_column_name="creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )

    op.alter_column(
        "keys",
        "last_modified_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.drop_constraint("keys_orders_id_fk", "keys", type_="foreignkey")
    op.drop_column("keys", "purchase_id")

    op.alter_column(
        "orders",
        "create_date",
        new_column_name="creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.alter_column(
        "orders",
        "last_changed",
        new_column_name="last_modified_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )

    op.alter_column(
        "products_vendors",
        "added",
        new_column_name="creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )
    op.alter_column(
        "products_vendors",
        "last_changed",
        new_column_name="last_modified_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )

    op.alter_column(
        "unsubscribed",
        "create_date",
        new_column_name="creating_date",
        existing_type=postgresql.TIMESTAMP(precision=6),
        nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
