"""added products_groups

Revision ID: 978a3bd54d2b
Revises: d03c94b20770
Create Date: 2023-05-16 15:33:40.307217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "978a3bd54d2b"
down_revision = "d03c94b20770"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_groups_id"), "products_groups", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_groups_id"), table_name="products_groups")
    op.drop_table("products_groups")
    # ### end Alembic commands ###
