"""fix tables22

Revision ID: c0b7114f9d30
Revises: e2ac95e74795
Create Date: 2023-05-13 13:42:19.602282

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c0b7114f9d30"
down_revision = "e2ac95e74795"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "is_subscription", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "is_subscription", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
