"""delete coupun

Revision ID: d03c94b20770
Revises: ef035322c4fe
Create Date: 2023-05-16 11:03:59.078210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d03c94b20770"
down_revision = "ef035322c4fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "coupon")
    op.drop_column("products", "remove_from_cross_selling_list")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "remove_from_cross_selling_list",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("coupon", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
