"""fix tables2

Revision ID: e2ac95e74795
Revises: 7ad587ad0fd1
Create Date: 2023-05-13 13:40:10.943842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2ac95e74795"
down_revision = "7ad587ad0fd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "is_subscribtion",
        new_column_name="is_subscription",
        existing_type=postgresql.BOOLEAN,
        nullable=True,
    )
    op.alter_column(
        "products",
        "is_subscribtion",
        new_column_name="is_subscription",
        existing_type=postgresql.BOOLEAN,
        nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
