"""product vendor description change type to str

Revision ID: ef035322c4fe
Revises: 3bc0f5fcde71
Create Date: 2023-05-14 12:37:20.035904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef035322c4fe"
down_revision = "3bc0f5fcde71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    alter table products_vendors
    alter column description type varchar(2048) using description::varchar(2048);
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
